Corner cases handling
travis-ci/travis-web pull request #2541
Opened 2020-09-14 19:44 UTC by piotrmilcarz

2020-09-15 14:06 UTC, artursmirnov requested changes
Hey @piotrmilcarz, thank you for the contribution! I have some comments code-wise, please take a look when you have a chance.

Apart from that, could you please also add a simple acceptance test that briefly checks that warning message shows up when it should and that modal window works as expected.

Also, could you please provide some instructions that would allow to test this PR in action? We have pricing branch deployed to staging API and billing. Although, it seems like there's some more set up needs to be done, does it?

Thank you!

2020-09-18 15:24 UTC, piotrmilcarz commented on app/templates/components/dialogs/switch-to-free-modal.hbs
> +                    (gt this.subscription.addonUsage.private.remainingCredits 0))}}
👍

2020-09-18 15:48 UTC, artursmirnov commented on app/models/v2-subscription.js
> +  }).drop(),
This feedback is not implemented. @piotrmilcarz it should be easy to implement, could you please take a look?

2020-09-18 15:53 UTC, piotrmilcarz commented on app/models/v2-subscription.js
> +  }).drop(),
I had to miss it.
Refactored now.

2020-09-18 15:59 UTC, artursmirnov approved these changes
@piotrmilcarz looks good to me now! Thank you for implementing the feedback 👍

2020-09-18 16:24 UTC, artursmirnov commented on app/templates/components/dialogs/switch-to-free-modal.hbs
> +        {{log }}
Could you please remove this one? 
```suggestion
```

2020-09-18 16:34 UTC, artursmirnov approved these changes

2020-09-18 16:38 UTC, merged